mysql:
  host: localhost
  port: 3306
  db: cc_db
  username: root
  password: chen0211
  log_level: dev
  config: "charset=utf8mb4&parseTime=True&loc=Local"
logger:
  level: info
  prefix: '[cc_project]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2024-08-01"
  title: CryptoCat
  version: "1.0"
  email: CryptoCat.cc1@gmail.com
  name: cc
  job: Software Engineer
  addr: Singapore
  slogan: CryptoCat
qq:
  app_id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: CryptoCat
  cdn: xx://xx.xx.com/
  zone: xx
  prefix: ""
  size: 5
email:
  host: ""
  port: 0
  user: ""
  password: ""
  default_from_email: CryptoCat
  use_ssl: false
  user_tls: false
jwt:
  public_key_path: "C:/Users/17772957183/AppData/Roaming/crypto_key/public_key.pem"
  private_key_path: "C:/Users/17772957183/AppData/Roaming/crypto_key/private_key.pem"
  expires: 2
  issuer: cc
upload_image:
  size: 2
  path: uploadFile/images
redis:
  ip: "127.0.0.1"
  port: 6379
  password: ""
  pool_size: 100
es:
  host: "http://127.0.0.1"
  port: 9200
  username:
  password:

